CREATE TABLE EMPLOYEE_PAYROLL
(
	ID INT IDENTITY,
	NAME VARCHAR(20),
	SALARY INT,
	START_DATE DATE
)
INSERT INTO EMPLOYEE_PAYROLL VALUES('JP',20000,GETDATE())
INSERT INTO EMPLOYEE_PAYROLL VALUES('BILL',26000,GETDATE())
INSERT INTO EMPLOYEE_PAYROLL VALUES('MANSI',29000,GETDATE(),'F')

SELECT SUM(SALARY) AS SUMMATION , AVG(SALARY) AS AVGERAGE ,MIN(SALARY) AS MINIMUM, MAX(SALARY)
FROM EMPLOYEE_PAYROLL
