CREATE TABLE EMPLOYEE_PAYROLL
(
	ID INT IDENTITY,
	NAME VARCHAR(20),
	SALARY INT,
	START_DATE DATE
)
INSERT INTO EMPLOYEE_PAYROLL VALUES('JP',20000,GETDATE())
INSERT INTO EMPLOYEE_PAYROLL VALUES('BILL',26000,GETDATE())

ALTER TABLE EMPLOYEE_PAYROLL
ADD GENDER CHAR


UPDATE EMPLOYEE_PAYROLL
SET GENDER = 'M'
WHERE NAME = 'Bill'

SELECT * FROM EMPLOYEE_PAYROLL
