CREATE TABLE EMPLOYEE_PAYROLL
(
	ID INT IDENTITY,
	NAME VARCHAR(20),
	SALARY INT,
	START_DATE DATE
)
INSERT INTO EMPLOYEE_PAYROLL VALUES('JP',20000,GETDATE())
INSERT INTO EMPLOYEE_PAYROLL VALUES('BILL',26000,GETDATE())

SELECT * FROM EMPLOYEE_PAYROLL

SELECT SALARY 
FROM EMPLOYEE_PAYROLL
WHERE NAME = 'BILL'

SELECT *
FROM EMPLOYEE_PAYROLL
WHERE START_DATE > '2018-01-01' AND START_DATE < GETDATE();